export {
  getUser,
  createUser,
  updateUser,
  deleteUser,
  getNews,
  createNews,
  updateNews,
  deleteNews,
  get5News,
  destroyNews,
  restoreNews,
  getHistory,
  getHistoryByID,
  getLesson,
  createLesson,
  updateLesson,
  deleteLesson,
  getNotifications,
  createNotifications,
  updateNotifications,
  deleteNotifications,
  getBank,
  createBank,
  updateBank,
  getTransaction,
  createTransaction,
  getTransactionByEmail,
  getCombo,
  createCombo,
  updateCombo,
  deleteCombo,
  deleteBank
} from './connects';
export * from './Hooks';
